/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    "migration-check": MigrationCheck;
    media: Media;
    menu: Menu;
    category: Category;
    "menu-item": MenuItem;
    "modifier-group": ModifierGroup;
    "modifier-option": ModifierOption;
    "daily-availability": DailyAvailability;
    promotion: Promotion;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    "migration-check": MigrationCheckSelect<false> | MigrationCheckSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    category: CategorySelect<false> | CategorySelect<true>;
    "menu-item": MenuItemSelect<false> | MenuItemSelect<true>;
    "modifier-group": ModifierGroupSelect<false> | ModifierGroupSelect<true>;
    "modifier-option": ModifierOptionSelect<false> | ModifierOptionSelect<true>;
    "daily-availability": DailyAvailabilitySelect<false> | DailyAvailabilitySelect<true>;
    promotion: PromotionSelect<false> | PromotionSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences": PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    "payload-migrations": PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    "store-settings": StoreSetting;
  };
  globalsSelect: {
    "store-settings": StoreSettingsSelect<false> | StoreSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: "admin" | "owner";
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "migration-check".
 */
export interface MigrationCheck {
  id: number;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: number;
  name: string;
  slug: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  menu?: (number | null) | Menu;
  sortOrder: number;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-item".
 */
export interface MenuItem {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  basePrice: number;
  category: number | Category;
  availabilityType: "steamTable" | "madeToOrder";
  active?: boolean | null;
  image?: (number | null) | Media;
  modifierGroups?: (number | ModifierGroup)[] | null;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modifier-group".
 */
export interface ModifierGroup {
  id: number;
  label: string;
  selectionType: "pickOne" | "pickMany";
  required?: boolean | null;
  minSelection?: number | null;
  maxSelection?: number | null;
  pricingMode: "included" | "priced";
  options?: (number | ModifierOption)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modifier-option".
 */
export interface ModifierOption {
  id: number;
  label: string;
  priceDelta: number;
  group: number | ModifierGroup;
  updatedAt: string;
  createdAt: string;
}
/**
 * soldOut status hides the item from the storefront for that day. Steam-table items default to available unless a soldOut record exists.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-availability".
 */
export interface DailyAvailability {
  id: number;
  date: string;
  menuItem: number | MenuItem;
  status: "available" | "soldOut";
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotion".
 */
export interface Promotion {
  id: number;
  name: string;
  applicationType: "auto" | "code";
  code?: string | null;
  discountType: "percent" | "fixed";
  value: number;
  scope: "order" | "category";
  category?: (number | null) | Category;
  validFrom?: string | null;
  validUntil?: string | null;
  minOrderValue?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "users";
        value: number | User;
      } | null)
    | ({
        relationTo: "migration-check";
        value: number | MigrationCheck;
      } | null)
    | ({
        relationTo: "media";
        value: number | Media;
      } | null)
    | ({
        relationTo: "menu";
        value: number | Menu;
      } | null)
    | ({
        relationTo: "category";
        value: number | Category;
      } | null)
    | ({
        relationTo: "menu-item";
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: "modifier-group";
        value: number | ModifierGroup;
      } | null)
    | ({
        relationTo: "modifier-option";
        value: number | ModifierOption;
      } | null)
    | ({
        relationTo: "daily-availability";
        value: number | DailyAvailability;
      } | null)
    | ({
        relationTo: "promotion";
        value: number | Promotion;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "migration-check_select".
 */
export interface MigrationCheckSelect<T extends boolean = true> {
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category_select".
 */
export interface CategorySelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  menu?: T;
  sortOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-item_select".
 */
export interface MenuItemSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  basePrice?: T;
  category?: T;
  availabilityType?: T;
  active?: T;
  image?: T;
  modifierGroups?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modifier-group_select".
 */
export interface ModifierGroupSelect<T extends boolean = true> {
  label?: T;
  selectionType?: T;
  required?: T;
  minSelection?: T;
  maxSelection?: T;
  pricingMode?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modifier-option_select".
 */
export interface ModifierOptionSelect<T extends boolean = true> {
  label?: T;
  priceDelta?: T;
  group?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-availability_select".
 */
export interface DailyAvailabilitySelect<T extends boolean = true> {
  date?: T;
  menuItem?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotion_select".
 */
export interface PromotionSelect<T extends boolean = true> {
  name?: T;
  applicationType?: T;
  code?: T;
  discountType?: T;
  value?: T;
  scope?: T;
  category?: T;
  validFrom?: T;
  validUntil?: T;
  minOrderValue?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings".
 */
export interface StoreSetting {
  id: number;
  storeName: string;
  isOpen?: boolean | null;
  weeklyHours?:
    | {
        day: "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun";
        open?: string | null;
        close?: string | null;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  dailyOverrides?:
    | {
        date: string;
        closed?: boolean | null;
        open?: string | null;
        close?: string | null;
        id?: string | null;
      }[]
    | null;
  timezone: string;
  taxRate?: number | null;
  leadTimeMinutes?: number | null;
  slotIntervalMinutes?: number | null;
  tipPresets?:
    | {
        value: number;
        id?: string | null;
      }[]
    | null;
  address?: string | null;
  phone?: string | null;
  pickupInstructions?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings_select".
 */
export interface StoreSettingsSelect<T extends boolean = true> {
  storeName?: T;
  isOpen?: T;
  weeklyHours?:
    | T
    | {
        day?: T;
        open?: T;
        close?: T;
        closed?: T;
        id?: T;
      };
  dailyOverrides?:
    | T
    | {
        date?: T;
        closed?: T;
        open?: T;
        close?: T;
        id?: T;
      };
  timezone?: T;
  taxRate?: T;
  leadTimeMinutes?: T;
  slotIntervalMinutes?: T;
  tipPresets?:
    | T
    | {
        value?: T;
        id?: T;
      };
  address?: T;
  phone?: T;
  pickupInstructions?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
